"""
Core system constants for Touchless Brightness Control.
"""
from enum import Enum

class GestureState(str, Enum):
    NO_HAND = "NO_HAND"
    HAND_DETECTED = "HAND_DETECTED"
    GESTURE_ACTIVE = "GESTURE_ACTIVE"
    GESTURE_INVALID = "GESTURE_INVALID"
    CALIBRATING = "CALIBRATING"
    PAUSED = "PAUSED"

# MediaPipe Hand Landmark Indexes
LANDMARK_WRIST = 0
LANDMARK_THUMB_TIP = 4
LANDMARK_INDEX_TIP = 8
LANDMARK_MIDDLE_TIP = 12
LANDMARK_RING_TIP = 16
LANDMARK_PINKY_TIP = 20

# Default bounds
DEFAULT_MIN_BRIGHTNESS = 10
DEFAULT_MAX_BRIGHTNESS = 100
DEFAULT_MIN_DISTANCE = 0.03
DEFAULT_MAX_DISTANCE = 0.25
DEFAULT_SMOOTHING_ALPHA = 0.2
DEFAULT_UPDATE_THRESHOLD = 2.0
